on:
  push:
    tags:
      - 'v*'

permissions: write-all

name: Latest Release

defaults:
  run:
    shell: bash

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goosarch:
          - 'linux/386'
          - 'linux/amd64'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Get OS and arch info
      run: |
        GOOSARCH=${{matrix.goosarch}}
        GOOS=${GOOSARCH%/*}
        GOARCH=${GOOSARCH#*/}
        FLAGS="-ldflags=-s"
        EXT=$([ "$GOOS" = "windows" ] && echo ".exe" || echo "")
        BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH$EXT
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
        echo "GOOS=$GOOS" >> $GITHUB_ENV
        echo "GOARCH=$GOARCH" >> $GITHUB_ENV
        echo "FLAGS=$FLAGS" >> $GITHUB_ENV
    - name: Build
      run: |
        go build -o "$BINARY_NAME" $FLAGS -v
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ${{env.BINARY_NAME}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
